### ISSUE TITLE
Dump UMA region using DMA tool (e.g. inception)?

### ISSUE THREAD

**Issue by sakaki-** [skochinsky/papers#1]
Hi Igor - very interesting work!

I noted in your 2014 papers you had mentioned various ways of trying to dump the UMA region (cold boot etc) and was wondering if you'd tried a DMA tool like [carmaa/inception](https://github.com/carmaa/inception)?

This might also provide a way to inject bytecode if the UMA area contains Java code that is (Huffman) decompressed and after any signature checks etc., or at very least to crash the IME to see what happens next... but perhaps the UMA region is inaccessible to DMA altogether?

One other thought: what happens to the UMA region if the system is hibernated to disk?

Best, sakaki

**Comment by skochinsky** [comment]
I suspect DMA won't work since the requests are handled by the MCH (I think) and it would drop accesses to the UMA region. But if you have access to such a tool, I'd be interested to hear whether my theory is correct or not.
As for hibernation, since normally only the OS-accessible memory is saved, UMA won't be included into the hibernation file.

**Comment by sakaki-** [comment]
Yes, thought as much for the hibernation idea; am hoping to try out a DMA test on a rig in the next month or so, will let you know if anything comes of it.
BTW did you see this paper (and associated software) [Lest we forget: Cold-boot attacks on scrambled DDR3 memory](http://www.sciencedirect.com/science/article/pii/S1742287616300032)?

**Comment by skochinsky** [comment]
Yes, that's good work and might allow dumping the UMA on DDR3 boards, however I no longer have the setup to try it.

**Comment by sakaki-** [comment]
The authors do mention that some mainboard/cpu configurations appear to exhibit _constant_ scrambling of memory across cold reboots (page S70), for example the i5-760+MSI H55M-P33; in such a case (assuming some subset of the physical memory address is used as an index into the scrambler/s), one could presumably boot the machine with e.g. 1 RAM slot populated, freeze it, power off, (quickly) populate an additional RAM slot (assuming this could be done without tipping the thing into double-channel mode) and restart - what was the UMA region would then presumably be in the middle of the physical memory map, and could be dumped?

Anyway I guess I should just try some of this stuff rather than bothering you, apologies ><
