### ISSUE TITLE
Hi sir

### ISSUE THREAD

**Issue by katip55** [skochinsky/papers#3]
In IDA pro,i have a big structure like B7C2090. When i use it in __thiscall function,a far pointer like this[145680760],in asm view i see true variable but in pseudo it is shown wrong. I have been using H to correcten it but there are tos of it. And if that pull variable over memory address H doesnt work. Waiting for a certain suggestion. Thnx

**Comment by skochinsky** [comment]
This is not the place for IDA support, please use the official channels.
